added array of files needed to be checked
Signed-off-by: Adhishree Kadam <118783118+adhishreekadam@users.noreply.github.com>

diff --git a/.github/workflows/check-files.yml b/.github/workflows/check-files.yml
--- a/.github/workflows/check-files.yml
+++ b/.github/workflows/check-files.yml
@@ -1,1 +1,36 @@
+name: Check required files
 
+on:
+  pull_request:
+    branches: [ "main" ]
+  fork:
+    branches: [ "main" ]
+    
+
+jobs:
+  build:
+
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Check for required files
+      run: |
+        filesToCheck=(
+          "makefile"
+          "service.policy.json"
+          "deployment.policy.json"
+          "serviceTest.sh"
+          "service.json"
+          "pattern.json"
+        )
+
+        for file in "${filesToCheck[@]}"; do
+          if [ ! -f "$file" ]; then
+            echo "Error: $file not found!"
+            exit 1
+          fi
+        done
+
+        echo "All required files are present."
